### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by zydczqcnydx** [RoboFlamingo/RoboFlamingo#11]
python=3.8
<img width="1595" alt="image" src="https://github.com/RoboFlamingo/RoboFlamingo/assets/76277077/0ea1a37d-3ba3-4541-8deb-ae301632b86d">
python=3.9
<img width="1238" alt="image" src="https://github.com/RoboFlamingo/RoboFlamingo/assets/76277077/4f938096-d703-4196-860b-221648a09fd7">

May I ask how to solve it？

**Comment by sun123-cmd** [comment]
Maybe you need to delete some modules of txt list, and install them independly

**Comment by jyue86** [comment]
Stick with the `python=3.8` conda env. I think a lot of the problems arise from not using pytorch cu+11.3, which I resolved with:
```
pip install  -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu113
```
