### ISSUE TITLE
Hyperparameters of the results in Table 1 of the paper

### ISSUE THREAD

**Issue by COST-97** [RoboFlamingo/RoboFlamingo#12]
Hello:
    Thank you so much for your excellent and interesting work!    
    For the results in Table 1 of the paper, are the hyperparameters used in your method the same? 
    Could you share the hyperparameters that got these results? 
    Thank you so much!

**Comment by Ericonaldo** [comment]
Hi, table 1 uses the results of the `M-3B-IFT` version of RoboFlamingo, the other training parameters should be the same as the default setup in this repo.
