### ISSUE TITLE
can this method use in real env directly?

### ISSUE THREAD

**Issue by lunalulu** [RoboFlamingo/RoboFlamingo#15]
thanks for your great job~

**Comment by Ericonaldo** [comment]
We have not released the version that is fine-tuned on real robot data. If you have such data, you can try to fine-tune and then deploy on your setup.

**Comment by lunalulu** [comment]
> We have not released the version that is fine-tuned on real robot data. If you have such data, you can try to fine-tune and then deploy on your setup.

thanks 
When will the real robot data training version be released?

**Comment by Ericonaldo** [comment]
We are making efforts to do that :) We also want it to be released as soon as possible.

**Comment by lunalulu** [comment]
> We are making efforts to do that :) We also want it to be released as soon as possible.

thanks very much~
please, How to collect real robot data? Can you give me some advice? For example, how to set the collection frequency? some scripts?

**Comment by Ericonaldo** [comment]
Actually I recommend you to refer to existing published works about that :)

**Comment by lunalulu** [comment]
> Actually I recommend you to refer to existing published works about that :)

for example?

**Comment by lunalulu** [comment]
> Actually I recommend you to refer to existing published works about that :)

Can the following real collection data be made open?
thanks very much

data_dir="/mnt/bn/robotics-data-hl/real_data/mode1_data_pick_place_001_1023/"

**Comment by lunalulu** [comment]
@Ericonaldo What is the approximate minimum number of trajectories per task that is suitable when collecting real-world operational data for fine-tuning a model?
thanks very much~
