### ISSUE TITLE
Test the model and data collection on Env ABCD

### ISSUE THREAD

**Issue by COST-97** [RoboFlamingo/RoboFlamingo#18]
Hello:
How can a model trained on Env ABCD be tested on Env A, B, C, and D?
Where can I find the required environment configuration files and language annotation files?

What's more, is it possible to use the trained model to collect data in the simulation, under the existing ABCD-like environment configuration and language annotations? Is it possible to give a simple demo of collecting data?

Thank you so much!

**Comment by Ericonaldo** [comment]
Hi, there is no such a configuration in the CALVIN benchmark, so you can make your own configuration. Have a reference to http://calvin.cs.uni-freiburg.de/
