### ISSUE TITLE
open-loop control？

### ISSUE THREAD

**Issue by lunalulu** [RoboFlamingo/RoboFlamingo#20]
![image](https://github.com/RoboFlamingo/RoboFlamingo/assets/40664601/129d099e-3955-4eef-8a47-26aadfcfeac9)
like above image，it come from the paper abstract，why is open-loop control（task）？Are we not supposed to solve a closed-loop task?

**Comment by Ericonaldo** [comment]
Hi, in our paper we mainly show close-loop control. 
Here by "open-loop control" we mean that RoboFlamingo has such a flexibility to do that as we have a light-weight, small policy head that can be directly deployed onto low-computation platforms with high frequency, and the large model part should be served as a cloud service run under a low frequency.

**Comment by lunalulu** [comment]
> Hi, in our paper we mainly show close-loop control. Here by "open-loop control" we mean that RoboFlamingo has such a flexibility to do that, as we have a light-weight, small policy head that can be directly deployed onto low-computation platforms with high frequency, and the large model part should be served as a cloud service run under a low frequency.

thanks very much ,
Consistent with my understanding！
