### ISSUE TITLE
Episode length

### ISSUE THREAD

**Issue by COST-97** [RoboFlamingo/RoboFlamingo#21]
Hello:
If I'm not mistaken, in the training phase, in all the tasks, the episode length is 64.
But intuitively there should be some differences between the different tasks, right?
What's more, at the testing stage, why is the maximum value of the length of the episode 360, and not 64?
Thank you so much!

**Comment by lixinghang12** [comment]
The episode length in the training data is set to 64. While the max step in evaluation is set to 360, which is same as in the previous CALVIN baselines.
