### ISSUE TITLE
about cotrain?

### ISSUE THREAD

**Issue by lunalulu** [RoboFlamingo/RoboFlamingo#23]
i saw the comment '--cotrain' and  the function 'train_one_epoch_calvin_cotrain'

But I didn't find where the call was made，are there any problems？

thanks for your reply

**Comment by Ericonaldo** [comment]
Cotrain codes have not been public as it was not cleaned. But they are in the next public plan.

**Comment by Ericonaldo** [comment]
Now co-trained codes are updated.
