### ISSUE TITLE
on what data were the hugging face model weights trained?

### ISSUE THREAD

**Issue by fredshentu** [RoboFlamingo/RoboFlamingo#25]
As the title said. Are those huggingface weights trained on split ABCD? Or just ABC?
https://huggingface.co/roboflamingo/RoboFlamingo

**Comment by fredshentu** [comment]
It will be great if you can also release the model that got trained on ABC only. We need a model trained on that data split to run some baselines.

**Comment by Ericonaldo** [comment]
Yeah, those are ABCD->D, and surely I think I can upload the ABC->D in a week.

**Comment by Ericonaldo** [comment]
Uploaded to HF.
