### ISSUE TITLE
dimmension of state,15 or 7 ???

### ISSUE THREAD

**Issue by lesjie-wen** [RoboFlamingo/RoboFlamingo#26]
l have read the code and found that the dimmension of state is ambigous.
First, in BCflamingo, the state_dim is 15 (default) and l ensure that no specified state_dim when create this model.
![image](https://github.com/RoboFlamingo/RoboFlamingo/assets/53989593/8e123805-227b-46a2-9cbe-bfdadea88a3d)
And in action head, the state_dim is 7. Which can not match when forward passing in BCflamingo.
![image](https://github.com/RoboFlamingo/RoboFlamingo/assets/53989593/8058c92e-2ab2-4f30-8a52-e6ac868ff100)
Can somebody help? l will appreciate that.

**Comment by lesjie-wen** [comment]
Okay, l notice that all the released scripts not set the use_state True which means the model will not use state_dim. So, if l want to use the state, l need to specify the state_dim in scripts.

**Comment by Ericonaldo** [comment]
It is true that we did not use any proprioceptive state for training, but you can choose either 15 or 7 for the state dim, and I think 7 means 'joints positions' or 'ee pose+gripper'.

**Comment by JayceWen** [comment]
Ok, thanks for your reply.
