### ISSUE TITLE
about training data？

### ISSUE THREAD

**Issue by lunalulu** [RoboFlamingo/RoboFlamingo#32]
If I understand correctly, all the data we need actually does not require the internal and external calibration parameters of the camera, right?

thanks very much

**Comment by Ericonaldo** [comment]
The public code is for training on simulated benchmark, so yes. If you need to deploy, you would need calibration.

**Comment by lunalulu** [comment]
> The public code is for training on simulated benchmark, so yes. If you need to deploy it onto real robots, you would need calibration.

I understand that we are an end-to-end network, from observation to action, so why is calibration needed on the actual robotic arm?
thanks for your reply~

**Comment by Ericonaldo** [comment]
You will need to calibrate like the camera position and latency. You will know that when you conduct real robot experiments.

**Comment by oym1994** [comment]
> You will need to calibrate like the camera position and latency. You will know that when you conduct real robot experiments.

Hi, we also face this problem. In theory, if we can guarantee the camera position and latency(something else) are same between training data collection and deployment period, there will need no calibration. I think you and your team must have met and solved much engineer problem. So would you mind introducing some practical experience for that? Many thanks.

**Comment by Ericonaldo** [comment]
It is case by case.
