### ISSUE TITLE
Questions about the action space in the Calvin dataset.

### ISSUE THREAD

**Issue by SatireY** [RoboFlamingo/RoboFlamingo#33]
Great job!
I notice that the output action in your code uses the MLPTanhHead output joint position, so the final output range should be [-1,1], but the maximum and minimum range of actions I see in the statistics.yaml file in the calvin dataset is
act_min_bound: [-0.432188, -0.545456, 0.293439, -3.141593, -0.811348, -3.141573, -1.]
act_max_bound: [0.42977, 0.139396, 0.796262, 3.141592, 0.638583, 3.141551, 1.]
How can this be explained? Looking forward to your reply.

**Comment by Ericonaldo** [comment]
I am not sure about the action space you use, in our work, the action space is the gripper pose and open/close, which is normalized in [-1,1].
