### ISSUE TITLE
Diffusion Model

### ISSUE THREAD

**Issue by COST-97** [RoboFlamingo/RoboFlamingo#43]
Hello:
I noticed that there is a diffusion model implementation in the code, and there are related comments in the code: _Diff still has bugs of loaded data mismatch_.
Is the problem solved now?
How is the performance of the diffusion model on calvin?
Moreover, the actions in _calvin_ have been normalized to -1~1, why do you need to use `model.diffusion_model.normalizer `additionally?
Thank you very much!

**Comment by Ericonaldo** [comment]
Hi, that part is not developed, and no recent plan to implement on this repo.
